version: "3"
services:
  db:
    container_name: mysql
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=health-plus
    ports:
      - 3306:3306
    restart: on-failure
  app:
    build: .
    container_name: health-plus
    ports:
      - 8080:8080
    volumes:
      - .:/web
    depends_on:
      - db
    restart: on-failure